@echo off
echo Budowanie Frontendu...
cd frontend && npm run build && cd ..
echo Kopiowanie plikow do statica...
xcopy /s /y frontend\dist\smart-helpdesk\browser\* src\main\resources\static\
echo Budowanie pliku JAR...
call mvnw.cmd clean package -DskipTests
echo Uruchamianie Dockera...
docker-compose up --build
pause